site_name: PINN-kit
site_description: A comprehensive toolkit for Physics-Informed Neural Networks
site_author: Shivani

nav:
  - Home: index.md
  - Getting Started:
    - Usage Guide: PINN_usage_guide.md
  - Examples:
    - Poisson Equation Tutorial: Poisson_PINN_Tutorial.md
    - Harmonic Oscillator Tutorial: Harmonic_Oscillator_PINN_Tutorial.md
  - API Reference:
    - Domain Module: Domain.md
    - PINN Module: PINN.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.svg
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - toc.follow
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shivani/PINN-kit

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/`|]+'
      prebuild_index: true
      indexing: 'full'
  - git-revision-date-localized:
      enable_creation_date: true

repo_url: https://github.com/fraqtal-technologies/PINN-kit
repo_name: GitHub

docs_dir: docs 